#!/bin/bash

npkg="$1"

if [[ -z "$npkg" ]]; then
    echo -e "

Helps properly configure the proprietary Nvidia drivers on Ubuntu.

  You need to provide the nvidia driver package as the first argument

  It will look something like:
     nvidia-367  # Where '367' will change over time
  ... and can be found using:
     aptitude search nvidia | grep 'nvidia-[0-9]* '

  For newer versions of Ubuntu the X server and this driver are not playing
  nicely together. In my case, the X server failed to start at all.

  The executed command used here are all taken from @user94959's
  answer on StackExchange:

    https://unix.stackexchange.com/a/298841

"
    exit
fi

echo "Removing old Nvidia and Nouveau drivers"

## purged system of old or broken configs by removing the following
sudo apt-get purge \
    nvidia*    \
    *nouveau*  \
    bumblebee* \

echo "Installing Nvidia drivers"

sudo apt-get install \
    "$npkg"         \
    primus          \
    nvidia-settings \ 
    nvidia-profiler \
    nvidia-visual-profiler

echo "Launching Nvidia's xconfig tool"

## Use nvidia-xconfig
sudo /usr/lib/$npkg/bin/nvidia-xconfig

echo "From @user94959 :

  This should now hopefully execute and generate the proper xorg.conf
  file into /etc/X11/ directory. If there is still another xorg.conf
  file(s), make sure you find the new one, this is easily identifiable
  since nvidia-xconfig generates a timestamp in the new xorg.conf file
  which should look something like this

  # nvidia-xconfig: X configuration file generated by nvidia-xconfig
  # nvidia-xconfig:  version 367.35  (buildmeister@swio-display-x64-rhel04-01)  Mon Jul 11 23:51:45 PDT 2016

  You can probably safely delete the old xorg-conf files that do not
  have this timestamp in them.

  Next open up NVIDIA X Server Settings and select

  # NVIDIA (Performance Mode)

  then reboot and you should be done. If you also have the
  nvidia-prime-applet installed then on your next reboot you should
  now see the NVIDIA icon in your menu bar to show it's active.

";


