#!/bin/bash

## It's great that Linux has fonts supporting a wide range of
## character sets. However, having over 200 language-specific fonts
## I'll never use makes font navigation a major pain in tools like
## LibreOffice.


unwanted=(
    "aakar"
    "Abyssinica SIL"
    "AbyssinicaSIL"
    "Ani"
    "AnjaliOldLipi"
    "Chandas"
    "Chilanka"
    "Droid Sans Fallback"
    "Dyuthi"
    "Gargi"
    "Garuda"
    "Gubbi"
    "Jamrul"
    "KacstArt"
    "KacstBook"
    "KacstDecorative"
    "KacstDigital"
    "KacstFarsi"
    "KacstLetter"
    "KacstNaskh"
    "KacstOffice"
    "KacstOne"
    "KacstPen"
    "KacstPoster"
    "KacstQurn"
    "KacstScreen"
    "KacstTitle"
    "KacstTitleL"
    "Kalapi"
    "Kalimati"
    "Karumbi"
    "Keraleeyam"
    "Khmer OS"
    "Khmer OS System"
    "KhmerOS"
    "KhmerOSsys"
    "Kinnari"
    "Laksaman"
    "Lato"
    "Likhan"
    "LKLUG"
    "Loma"
    "Manjari"
    "Meera"
    "Mitra Mono"
    "mry_KacstQurn"
    "Mukti Narrow"
    "Nakula"
    "Navilu"
    "Norasi"
    "Noto Kufi Arabic"
    "Noto Mono"
    "Noto Naskh Arabic"
    "Noto Naskh Arabic UI"
    "Noto Nastaliq Urdu"
    "Noto Sans"
    "Noto Sans Adlam"
    "Noto Sans Adlam Unjoined"
    "Noto Sans Anatolian Hieroglyphs"
    "Noto Sans Arabic"
    "Noto Sans Arabic UI"
    "Noto Sans Armenian"
    "Noto Sans Avestan"
    "Noto Sans Balinese"
    "Noto Sans Bamum"
    "Noto Sans Batak"
    "Noto Sans Bengali"
    "Noto Sans Bengali UI"
    "Noto Sans Brahmi"
    "Noto Sans Buginese"
    "Noto Sans Buhid"
    "Noto Sans Canadian Aboriginal"
    "Noto Sans Carian"
    "Noto Sans Chakma"
    "Noto Sans Cham"
    "Noto Sans Cherokee"
    "Noto Sans CJK JP"
    "Noto Sans CJK KR"
    "Noto Sans CJK SC"
    "Noto Sans CJK TC"
    "Noto Sans Coptic"
    "Noto Sans Cuneiform"
    "Noto Sans Cypriot"
    "Noto Sans Deseret"
    "Noto Sans Devanagari"
    "Noto Sans Devanagari UI"
    "Noto Sans Display"
    "Noto Sans Egyptian Hieroglyphs"
    "Noto Sans Ethiopic"
    "Noto Sans Georgian"
    "Noto Sans Glagolitic"
    "Noto Sans Gothic"
    "Noto Sans Gujarati"
    "Noto Sans Gujarati UI"
    "Noto Sans Gurmukhi"
    "Noto Sans Gurmukhi UI"
    "Noto Sans Hanunoo"
    "Noto Sans Hebrew"
    "Noto Sans Imperial Aramaic"
    "Noto Sans Inscriptional Pahlavi"
    "Noto Sans Inscriptional Parthian"
    "Noto Sans Javanese"
    "Noto Sans Kaithi"
    "Noto Sans Kannada"
    "Noto Sans Kannada UI"
    "Noto Sans Kayah Li"
    "Noto Sans Kharoshthi"
    "Noto Sans Khmer"
    "Noto Sans Khmer UI"
    "Noto Sans Lao"
    "Noto Sans Lao UI"
    "Noto Sans Lepcha"
    "Noto Sans Limbu"
    "Noto Sans Linear B"
    "Noto Sans Lisu"
    "Noto Sans Lycian"
    "Noto Sans Lydian"
    "Noto Sans Malayalam"
    "Noto Sans Malayalam UI"
    "Noto Sans Mandaic"
    "Noto Sans Meetei Mayek"
    "Noto Sans Mongolian"
    "Noto Sans Mono"
    "Noto Sans Mono CJK JP"
    "Noto Sans Mono CJK KR"
    "Noto Sans Mono CJK SC"
    "Noto Sans Mono CJK TC"
    "Noto Sans Myanmar"
    "Noto Sans Myanmar UI"
    "Noto Sans New Tai Lue"
    "Noto Sans NKo"
    "Noto Sans Ogham"
    "Noto Sans Ol Chiki"
    "Noto Sans Old Italic"
    "Noto Sans Old Persian"
    "Noto Sans Old South Arabian"
    "Noto Sans Old Turkic"
    "Noto Sans Oriya"
    "Noto Sans Oriya UI"
    "Noto Sans Osage"
    "Noto Sans Osmanya"
    "Noto Sans Phags Pa"
    "Noto Sans Phoenician"
    "Noto Sans Rejang"
    "Noto Sans Runic"
    "Noto Sans Samaritan"
    "Noto Sans Saurashtra"
    "Noto Sans Shavian"
    "Noto Sans Sinhala"
    "Noto Sans Sinhala UI"
    "Noto Sans Sundanese"
    "Noto Sans Syloti Nagri"
    "Noto Sans Syriac Eastern"
    "Noto Sans Syriac Estrangela"
    "Noto Sans Syriac Western"
    "Noto Sans Tagalog"
    "Noto Sans Tagbanwa"
    "Noto Sans Tai Le"
    "Noto Sans Tai Tham"
    "Noto Sans Tai Viet"
    "Noto Sans Tamil"
    "Noto Sans Tamil UI"
    "Noto Sans Telugu"
    "Noto Sans Telugu UI"
    "Noto Sans Thaana"
    "Noto Sans Thai"
    "Noto Sans Thai UI"
    "Noto Sans Tibetan"
    "Noto Sans Tifinagh"
    "Noto Sans Ugaritic"
    "Noto Sans Vai"
    "Noto Sans Yi"
    "Noto Serif Armenian"
    "Noto Serif Bengali"
    "Noto Serif CJK JP"
    "Noto Serif CJK KR"
    "Noto Serif CJK SC"
    "Noto Serif CJK TC"
    "Noto Serif Devanagari"
    "Noto Serif Ethiopic"
    "Noto Serif Georgian"
    "Noto Serif Gujarati"
    "Noto Serif Hebrew"
    "Noto Serif Kannada"
    "Noto Serif Khmer"
    "Noto Serif Lao"
    "Noto Serif Malayalam"
    "Noto Serif Myanmar"
    "Noto Serif Sinhala"
    "Noto Serif Tamil"
    "Noto Serif Telugu"
    "Noto Serif Thai"
    "Padauk"
    "Padauk Book"
    "padmaa"
    "padmaa-Bold.1.1"
    "Pagul"
    "Phetsarath OT"
    "Pothana2000"
    "Purisa"
    "Rachana"
    "RaghuMalayalam"
    "Rekha"
    "Saab"
    "Sahadeva"
    "Samanata"
    "Samyak Devanagari"
    "Samyak Gujarati"
    "Samyak Malayalam"
    "Samyak Tamil"
    "Sarai"
    "Sawasdee"
    "Suruma"
    "Tibetan Machine Uni"
    "Tlwg Mono"
    "Tlwg Typewriter"
    "TlwgTypewriter"
    "Tlwg Typist"
    "Tlwg Typo"
    "Umpush"
    "Uroob"
    "utkal"
    "Vemana2000"
    "Waree"
)

fm=$(which font-manager)

if [[ "$fm" == "" ]]; then
    echo "Please install font-manager:
  sudo apt-get install font-manager
"
    exit;
fi

echo "Disabling fonts..."
for u in "${unwanted[@]}"
do
    ## Initially I tried doing this via sudo removal of font
    ## directories. This works nicer, is easily reversible, and does
    ## not require sudo:
    
    ## https://superuser.com/a/428954
    font-manager --disable "$u"
    echo "    $u"
done

